config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos
  resources :photos
  resources :statics, only: [:index]
  resources :contacts, only: [:index, :create]

  root "statics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  after_create :send_email

  def send_email
    ContactMailer.send_message(self).deliver
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
   mount_uploader :picture, PictureUploader
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = Contact.create(contact_params)
    flash[:notice] = 'Ваше письмо отправлено!'
    redirect_to action: :index
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :theme, :body)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      redirect_to statics_path(page: :gallery), notice: 'Photo was successfully created.'
    else
      render :new
    end
  end
  
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to statics_path(page: :gallery)
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:picture, :describtion)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def index
    @page = params[:page] || 'home'
    if @page == "gallery"
      @photos = Photo.all
      @videos = Video.all
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to statics_path(page: :gallery), notice: 'Video was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @video.destroy
    respond_to do |format|
      format.html {  redirect_to statics_path(page: :gallery)}
      format.json { head :no_content }
    end
  end


  private
   def set_video
      @video = Video.find(params[:id])
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/contacts/_form.html.haml
%form{:class => "contact-us-form", :action => contacts_path, :method => 'POST'}
  %input{:name => "contact[name]", :type => "text", :placeholder => "Имя"}
  %input{:name => "contact[theme]", :type => "text", :placeholder => "Тема сообщения"}
  %input{:name => "contact[email]", :type => "email", :placeholder => "Email"}
  %textarea{:name => "contact[body]", :id => "", :rows => "12", :placeholder => "Ваше сообщение"}
  = hidden_field_tag :authenticity_token, form_authenticity_token
  %div{:class => "contact-us-form-actions"}
    %input{:type => "submit", :class => "button", :value => "Send it"}

app/views/contacts/index.html.haml
%section{:class => "contact-us-section"}
  .row.medium-unstack
    .columns.contact-us-section-left
      %h1.contact-us-header
        Наши контакты
      .responsive-embed
        ='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2647.443721640863!2d35.003075451366236!3d48.42882303870776!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40dbe35eb81bd8cf%3A0x988582f69db59fb2!2sAkademika+Yanhelya+St%2C+8%2C+Dnipropetrovs&#39;k%2C+Dnipropetrovsk+Oblast%2C+49000!5e0!3m2!1sen!2sua!4v1516927410926" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>'.html_safe
      %ul.contact-us-list
        %li.address Украина, Днепр, ул. Академика Янгеля, 8
        %li{:class => "email"} 
          %a{:href => "mailto:  "} powerfulkids18@gmail.com
        %li{:class => "phone"}     +38 066 008 08 55; 
        %li{:class => "phone"}     +38 098 589 94 97.
    .columns.contact-us-section-right
      %h1.contact-us-header Форма обратной связи 
      = render 'contacts/form'

app/views/layouts/_footer.html.erb
<div id="engadget-footer-contact-details-container">
    <footer id="engadget-footer-contact-details">
        <div class="footer-left">
            <div class="contact-details">
                <ul>
                    <li><i class="fa fa-phone fa-lg" aria-hidden="true"></i> +38 066 008 08 55;</li>
                    <li><i class="fa fa-phone fa-lg" aria-hidden="true"></i> +38 098 589 9497.</li>
                    <br>
                    <li><i class="fa fa-phone fa-lg" aria-hidden="true"></i> Наш адрес</a></li>
                    <li><i class="fa fa-map-marker fa-lg" aria-hidden="true" align="left"></i> Украина, Днепр
                    ул. Академика Янгеля, 8</li>
                </ul>
            </div>
        </div>
        <div class="footer-left" style="width: 33%;">
            <div class="contact-details">
                <ul>
                    <li>&copy; 2017 No rights reserved</li>
                </ul>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<header class="subnav-hero-section">
  <h1 class="subnav-hero-headline">
    <small>КЛУБ ФИЗИЧЕСКОГО РАЗВИТИЯ</small> "POWERFUL KIDS"
    <img src="https://s3.amazonaws.com/www.dneprpowerkids.ua/imgonline-com-ua-Transparent-backgr-7upkeH3Gfvsk.jpg" height="65px" width="65px" float="right"></img>
  </h1>
  <ul class="menu menu-hover-lines">
    <li><a class="active" href="<%= root_path(page: 'home') %>">Главная</a></li>
    <li><a href="<%= root_path(page: 'about_us') %>">О нас</a></li>
    <li><a href="<%= root_path(page: 'about_coatch') %>">Тренеры</a></li>
    <li><a href="<%= root_path(page: 'rules') %>">Правила</a></li>
    <li><a href="<%= root_path(page: 'shedule') %>">Расписание</a></li>
    <li><a href="<%= root_path(page: 'gallery') %>">Галерея</a></li>
    <% if user_signed_in? %>
      <li><a href="<%= photos_path %>">Фотографии</a></li>
      <li><a href="<%= videos_path %>">Видео</a></li>
    <% end%>
    <li><a href="<%= contacts_path %>">Контакты</a></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Dnepr Power Kids" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% if current_user %>
      <%= 'Привет, ' + current_user.email %>
      <%= link_to "Выйти", destroy_user_session_path, method: :delete%>
    <% end %>  
    <%= render "layouts/header" %>
    <div class="content">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body

    = yield

app/views/photos/_form.html.haml
= simple_form_for(@photo, multiple: true) do |f|
  = f.error_notification

  .form-inputs
    = f.file_field :picture
    = f.input :describtion

  .form-actions
    = f.button :submit

app/views/photos/_photo.html.haml
%div.cont
  %img.tent{src: photo.picture.url}

app/views/photos/index.html.haml
%h1 Listing photos
= link_to 'New Photo', new_photo_path, style: "margin-bottom: 20px;"

%table
  %thead
    %tr
      %th Name
      %th Body
      %th
      %th
      %th

  %tbody
    - @photos.each do |photo|
      %tr
        %td
          %img{src: photo.picture.thumb.url}
        %td= photo.describtion
        %td= link_to 'Show', photo
        %td= link_to 'Edit', edit_photo_path(photo)
        %td= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', photos_path

app/views/statics/_about_coatch.html.haml
%div{:class => "about-the-author"}
  %div{:class => "row"}
    %div{:class => "small-12 medium-4 columns"}
      %div{:class => "author-image"}
        %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/QgfEoQuY1Hc.jpg"}
      %div{:class => "author-social"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg facebook"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-facebook fa-stack-1x fa-inverse"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg twitter"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-twitter fa-stack-1x fa-inverse"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg linkedin"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-linkedin fa-stack-1x fa-inverse"}
    %div{:class => "small-12 medium-8 columns"}
      %h4{:class => "separator-left"} Шевченко Владислав Владимирович
      %ul
        %li Спортивные достижения: 
        %li Бронзовый призер первенства ДЮСШ КСК «Шинник» по прыжкам на батуте -2004 г. Днепропетровск;
        %li Серебряный призер в турнире ДЮСШ КСК «Шинник» по прыжкам на батуте -2004 г. Днепропетровск;
        %li Бронзовый призер в первенстве ДЮСШ КСК «Шинник» по прыжкам на батуте -2005 г. Днеперопетровск;
        %li Победитель первенства ДЮСШ КСК «Шинник» -2005 г. Днепропетровск;
        %li Бронзовый призер первенства СДЮСШОР № 2 по прыжкам на батуте -2009 г. Днепропетровск;
        %li Бронзовый призер чемпионата области по прыжкам на батуте -2009 г. Днепропетровск;
        %li Бронзовый призер первенства СДЮСШОР № 2 по прыжкам на батуте -2009 г. Днепропетровск;
        %li Серебряный призер первенства СДЮСШОР № 2 по прыжкам на батуте -2010 г. Днепропетровск;
        %li Серебряный призер СДЮСШОР №2 в соревнованиях по прыжкам на батуте -2010 г. Днепропетровск;
        %li Бронзовый призер первенства СДЮСШОР № 2 по прыжкам на батуте -2010 г. Днепропетровк;
        %li Серебряный призер в командных соревнованиях чемпионата Украины по прыжкам на батуте -2010 г. Славутич;
        %li Бронзовый призер в V I летних юношеских спортивных играх области по прыжкам на батуте в индивидуальных упражнениях. -2011 г. Днепропетровск;
        %li Серебряный призер в первенстве СДЮСШОР № 2 по прыжкам на батуте -2011 г. Днепропетровск;
        %li Бронзовый призер чемпионата области по прыжкам на батуте -2012 г. Днепропетровск;
        %li Бронзовый призер чемпионата области по прыжкам на батуте -2013 г. Днепропетровск;
        %li Победитель в Кубке Области по прыжкам на батуте -2013 г. Днепропетровск.
%br
%div{:class => "about-the-author"}
  %div{:class => "row"}
    %div{:class => "small-12 medium-4 columns"}
      %div{:class => "author-image"}
        %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/dqhalNxZI4I.jpg"}
      %div{:class => "author-social"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg facebook"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-facebook fa-stack-1x fa-inverse"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg twitter"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-twitter fa-stack-1x fa-inverse"}
        %a{:href => "#"}
          %span{:class => "fa-stack fa-lg linkedin"}
            %i{:class => "fa fa-circle fa-stack-2x"}
            %i{:class => "fa fa-linkedin fa-stack-1x fa-inverse"}
    %div{:class => "small-12 medium-8 columns"}
      %h4{:class => "separator-left"} Ротань Полина Александровна
      %ul
        %li Спортивные достижения: 
        %li Лауреат танцевального фестиваля "Изумрудный город";
        %li Лауреат ежегодного фестиваля "GLOBAL- DANCE";
        %li Лауреат фестиваля "Музыка Любви" Днепропетровской области;
        %li Лауреат "Ukrainian Dance Cup" Всеукраинский конкурс хореографии.
        

app/views/statics/_about_us.html.haml
%div{:align => "center"}
  %h4{:color => "white", :font-size => "48"} КЛУБ ФИЗИЧЕСКОГО РАЗВИТИЯ "POWERFUL KIDS" в Днепропетровске приглашает деток на групповые и индивидуальные тренировки.

%h3{:color => "white", :font-size => "40", :color => "", :font-style => "italic"} Мы предлагаем:
%div{:float => "center", :style => "font-size: 17px"}
  %div{:data-closable => nil, :class => "callout alert-callout-border success"}
    %bold Курс общей физической подготовки для улучшения здоровья

  %div{:data-closable => nil, :class => "callout alert-callout-border warning"}
    %bold Индивидуальный подход к каждому ребенку, а так же индивидуальная программа тренировок

  %div{:data-closable => nil, :class => "callout alert-callout-border success"}
    %bold Тренировки по принципу "CrossFit"
    %br (Кроссфит – это круговая тренировка (то есть, упражнения постоянно повторяются, как бы замыкаясь в цепочку), которая заключается в выполнении определенного 
    комплекса упражнений за минимальное время. Она имеет принципиальные отличия от обычных круговых тренировок, так как направленна на развитие сразу нескольких физических качеств, таких как сила, выносливость и ловкость. Тренировочную концепцию кроссфита можно назвать одной из лучших в развитии общей физической подготовки. Индивидуальный комплекс подбирается исходя из возможности спортсмена и оснащения зала.)

  %div{:data-closable => nil, :class => "callout alert-callout-border warning"}
    %bold Фитнес для малышей 
    %br (Занятия фитнесом способствуют здоровому физическому развитию малышей, правильному формирование опорно-двигательного аппарата и обеспечивают профилактику 
    наиболее распространенных недугов - плоскостопия и нарушения осанки. Также это позволит Вашему малышу сделать качественный скачок в развитии не только физической, но и психо-эмоциональной сферы, поскольку умение управлять своим телом требует соответствующего интеллектуального развития.)

  %div{:data-closable => nil, :class => "callout alert-callout-border success"}
    %bold А так же упражнения на гибкость и растяжку
  %div{:data-closable => nil, :class => "callout aler-callout-border warning"}
    %bold Занятия проводятся в двух оборудованных и уютных залах

app/views/statics/_gallery.html.haml
%div#photos.owl-carousel.owl-theme
  = render partial: "photos/photo", collection: @photos 
%br
%div#videos.owl-carousel.owl-theme
  = render partial: "videos/video", collection: @videos 

app/views/statics/_home.html.haml
%div{:class => "marketing-site-content-section"}
  %div{:class => "marketing-site-content-section-img"}
    %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/1+(120).jpg", :alt => ""}
  
  %div{:class => "marketing-site-content-section-block"}
    %h3{:class => "marketing-site-content-section-block-header"} Приглашаем деток в возрасте от 4 до 14 лет!
    %ul{:class => "marketing-site-content-section-block-subheader subheader dotless"}
      %li Индивидуальный подход к каждому ребенку;
      %li Интересные тренировки;
      %li Дружный коллектив;
      %li Интересные упражнения;
      %li Всестороннее развитие Вашего ребенка!


  

app/views/statics/_rules.html.haml
%div
  %div{:class => "basic-card", :align => "center"}
    %div{:class => "basic-card-image"}
      %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/0220).jpg"}
    %div{:class => " callout secondary"}
      %h5 Оплата
      %ul{:class => 'dotless'}
        %li Цена пробной (первой) тренировки - 50 грн.
        %li Стоимость разового занятия - 70 грн.
        %li Цена месячного абонимента составляет 350 грн!
      Оплата осуществляется в день приобретения абонимента в любой день месяца. Тренировки проводятся 2 раза в неделю по 1 часу.
      Перенос тренировки возможен и обсуждается в индивидуальном порядке с Вашим тренером.
      Не состоявшиеся по вине клуба тренировки не будут  включены в стоимость и будут перенесены. В других случаях  мы оставляем за собой право отметить пропущенную тренировку "прогулянной".

  %div{:class => "basic-card", :align => "center"}
    %div{:class => "basic-card-image"}
      %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/lA_jOQ44U60.jpg"}
    %div{:class => " callout secondary"}
      %h5 Форма
      %p Одевайте спортивную форму по сезону и приходите к нам!
      %br
      Детки без формы на тренировку допускаться не будут!
      

  %div{:class => "basic-card", :align => "center"}
    %div{:class => "basic-card-image"}
      %img{:src => "https://s3.amazonaws.com/www.dneprpowerkids.ua/x9OQLp58nDk.jpg"}
    %div{:class => " callout secondary"}
      %h5 Справка
      %p Главная цель тренировок - здоровье и хорошая физическая форма Вашего ребенка. 
      %br
      Поэтому, чтобы тренировки шли только в пользу, наличие справки о здоровье Вашего ребенка обязательно!
      В противном случае дети на тренировку допускаться не будут.
      К каждому ребенку мы подберем индивидуальную программу исходя из его функциональных и физических способностей.
    
    

app/views/statics/_shedule.html.haml
%table{:class => "table_blur"}
  %tr
    %th ул. Янгеля 8, клуб Елена
    %th ПН
    %th ВТ
    %th СР
    %th ЧТ
    %th ПТ
    %th СБ
    %th ВС
  %tr
    %td Старшая группа
    %td 
    %td 
    %td 16:00-17:00
    %td 
    %td 
    %td 15:00-16:00
    %td 
  %tr
    %td Младшая группа
    %td 16:00-17:00
    %td 
    %td 
    %td 
    %td 
    %td 14:00-15:00
    %td
%table{:class => "table_blur"}
  %tr
    %th ж/м Сокол-1, клуб Panda_go
    %th ПН
    %th ВТ
    %th СР
    %th ЧТ
    %th ПТ
    %th СБ
    %th ВС
  %tr
    %td Старшая группа
    %td 16:30-17:30
    %td 
    %td 
    %td 16:30-17:30 
    %td 
    %td 
    %td 
  %tr
    %td Младшая группа
    %td 16:30-17:30
    %td 
    %td 
    %td 16:30-17:30 
    %td 
    %td 
    %td

app/views/statics/index.html.haml
= render "statics/#{@page}"

app/views/videos/_form.html.haml
= simple_form_for(@video) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :body

  .form-actions
    = f.button :submit

app/views/videos/_video.html.haml
%div
  %div{style: 'width: 560px'}
    = video.body.html_safe

app/views/videos/index.html.haml
%h1 Listing videos
= link_to 'New Video', new_video_path

%table
  %thead
    %tr
      %th Name
      %th Body
      %th
      %th
      %th

  %tbody
    - @videos.each do |video|
      %tr
        %td= video.name
        %td= video.body
        %td= link_to 'Show', video
        %td= link_to 'Edit', edit_video_path(video)
        %td= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }

%br

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', photos_path